### ISSUE TITLE
What is the status of this project?

### ISSUE THREAD

**Issue by clintonb** [jazzband/django-sortedm2m#112]
The lack of development on this project in the past four months has lead to my, and others, wondering the state of this project. Is this project still maintained? If so, can we expand the group of maintainers authorized to merge and release code?

If this package is not maintained, can the following steps be taken?

1. Now: Update the README to reflect the state of the project, and request new maintainers.

2. Later: Transfer ownership of the project (including the PyPI package) to new maintainers.

3. Later: Update the README of this repo to point to the location of the new repo.

**Comment by clintonb** [comment]
@gregmuellegger

**Comment by fdintino** [comment]
I would gladly volunteer to help maintain. I think this would also be a good candidate for a @jazzband project.

**Comment by nemesisdesign** [comment]
@gregmuellegger it's cool there are so many people to help you out. I kindly suggest to follow their suggestion and appoint a few more maintainers to speed up the improvement of this useful django app.

**Comment by nemesisdesign** [comment]
@clintonb I think this issue can be closed

**Comment by clintonb** [comment]
I will leave it to @gregmuellegger to close as an official acknowledgement. He has yet to respond, and while the bust of activity to get Django 1.11 support is appreciated, it is still worth discussing the long-term maintenance of the project.

**Comment by rohithasrk** [comment]
@gregmuellegger It would be great if you could give maintenance rights to some of the other willing volunteers. We use this package in our software and sometimes face delays in releases. Please consider. Thank you :smile:

**Comment by riconnon** [comment]
+1 to the above on the idea of this becoming a jazzband project if @gregmuellegger is OK with that

**Comment by gregmuellegger** [comment]
.... oops haven't following all that here. Sorry for wasting everybodys time - that definitely wasn't my attention. Please go ahead with transfering it to Jazzband. I gave my approval over there https://github.com/jazzband/roadies/issues/150

**Comment by clintonb** [comment]
Thank you!

**Comment by richardbarran** [comment]
I think it's a good move as it means we keep the same Github repo (with issues and PRs) and also potentially we can have multiple maintainers for the project.
I've joined the Jazzband organisation, I suggest that other people interested in keeping this project alive do the same.
We could use a project lead (a BDFL?) to keep the code tidy and to organise releases. I'm not too keen on taking on that responsibility myself - I already help maintain 3 projects.
Does anyone want to volunteer for this position?

**Comment by gregmuellegger** [comment]
I'm not that aware of how the process of jazzband works. Feel free to ping me about permission grants etc for repo, pypi whatever either here or via twitter and I'll try to sort that out timely.

**Comment by clintonb** [comment]
Thank you, again, @gregmuellegger, for your service to the community in creating and maintaining this package! Once The PyPI maintainer is updated, this issue can be closed.

**Comment by gregmuellegger** [comment]
@clintonb Thanks for the kind words after the two years of waiting 😞 

I've just added jazzband as maintainer of the PyPI package.
