### ISSUE TITLE
Checkbox goes missing with boot strap theme 

### ISSUE THREAD

**Issue by rosehgal** [jazzband/django-sortedm2m#116]
<img width="1331" alt="screen shot 2017-12-05 at 3 18 51 pm" src="https://user-images.githubusercontent.com/21152070/33601305-d4d843de-d9d1-11e7-8c76-b61e8178b299.png">
<img width="1347" alt="screen shot 2017-12-05 at 3 18 41 pm" src="https://user-images.githubusercontent.com/21152070/33601316-df23cbba-d9d1-11e7-8cbc-d31db13fe615.png">

With the bootstrap-admin theme, check box goes missing on the admin interface. But after converting the input type class from checkbox to text, the input checkbox shows itself.

**Comment by seancallaway** [comment]
Also experiencing missing checkboxes when using Bootstrap (non-admin, though).
