### ISSUE TITLE
How to use the base_class?

### ISSUE THREAD

**Issue by iDevPy** [jazzband/django-sortedm2m#148]
I have a question about how to use the base_class. I tried looking into multiple places for an answer, but I cannot find any example. I believe that I need to override the class method, but I am not sure which one.

This is what I am doing:

```
class Author(models.Model):

    name = models.CharField(max_length=250)


class Article(models.Model):

    authors = SortedManyToManyField(Author,  base_class="ArticleAuthorsSort")


class ArticleAuthorsSort(models.Model):

    author = models.ForeignKey(Author, on_delete=models.CASCADE)

    article = models.ForeignKey(Article, on_delete=models.CASCADE)

    sort_value = models.PositiveSmallIntegerField()


    class Meta:

        ordering = ('sort_value',)


    def __str__(self):

        return self.sort_value
```

And this is the error I am getting:

```
File sortedm2m/fields.py", line 330, in create_sortable_many_to_many_intermediary_model

    '_sort_field_name': sort_field_name,

TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
```

**Comment by AlanCoding** [comment]
There's an example of `base_class` here

https://github.com/jazzband/django-sortedm2m/blob/5f357c20d60e0fe8bb9735ae5e0f30bab50982dc/example/testapp/models.py#L14-L21

And documented

https://github.com/jazzband/django-sortedm2m/blob/5f357c20d60e0fe8bb9735ae5e0f30bab50982dc/README.rst#L97-L114

I _only_ see testing of the `__str__` use described in the docs. I see no examples of using a `base_class` that defines new fields, and it is unclear if such a class should subclass `Model` or be a dumb mixin. The advice "You also could use it to add additional fields to the through model" is trouble without a corresponding test.

However, the advice here:

> consider *not* using sortedm2m but use a ordinary Django ManyToManyField and specify `your own through model`

Sounds like a failed middle-ground. Why not a _sorted_ m2m field and specify your own through model? An example exists in the tests right here:

https://github.com/jazzband/django-sortedm2m/blob/5f357c20d60e0fe8bb9735ae5e0f30bab50982dc/sortedm2m_tests/models.py#L32-L51

Thus, my high-level suggestion for your use class would be to replace `authors = SortedManyToManyField(Author,  base_class="ArticleAuthorsSort")` with `authors = SortedManyToManyField(Author,  through="ArticleAuthorsSort")`. This is a non-trivial change and requires a number of balancing changes to align the through fields and the "sort_value_field_name". However, in this case, you have a template to start with, the advice on the basic usage of through models in m2m fields is widely available on the internet.
