### ISSUE TITLE
"ModuleNotFoundError: No module named 'django.utils.six'" with Django 3.0

### ISSUE THREAD

**Issue by philgyford** [jazzband/django-sortedm2m#151]
I'm in the process of updating my project to Django 3.0 but using sortedm2m I get:

      File "/Users/phil/Projects/personal/django-ditto/.tox/py38-django30/lib/python3.8/site-packages/sortedm2m/forms.py", line 10, in <module>
        from django.utils.six import string_types
    ModuleNotFoundError: No module named 'django.utils.six'

Django 3.0 [drops support](https://docs.djangoproject.com/en/3.0/releases/3.0/#removed-private-python-2-compatibility-apis) for python 2 compatibility APIs, so I guess sortedm2m either needs to drop support for python 2, or explicitly include a non-Django instance of `six`?

**Comment by cqxu** [comment]
if use whitenoise, try to upgrade whitenoise:
  pip install whitenoise --upgrade

**Comment by clintonb** [comment]
This was resolved by #152.
