### ISSUE TITLE
[bug] `prefetch_related` stops working in Django 3.0

### ISSUE THREAD

**Issue by catriuspham** [jazzband/django-sortedm2m#159]
It used to work in Django 2.x, but now using `prefetch_related` on a SortedM2M fields make it an empty one.

**Comment by AlanCoding** [comment]
I added a new test here https://github.com/jazzband/django-sortedm2m/pull/208 and I'm not getting any hits. Maybe because you're using Django 2.x, we start testing with Django 3.0.
