### ISSUE TITLE
German translation missing in pypi package

### ISSUE THREAD

**Issue by tschale** [jazzband/django-sortedm2m#163]
It seems like the `de`-translations folder is missing in the pypi package. The downloaded wheel only contains `cs` and `fr` translations:
![image](https://user-images.githubusercontent.com/5681839/88203876-c308c700-cc4a-11ea-9025-3bc3e89dba23.png)

**Comment by clintonb** [comment]
I have confirmed this is an issue. When I build the sdist or bdist_wheel locally, all locales are included.

**Comment by clintonb** [comment]
This is fixed in 3.0.1.

**Comment by tschale** [comment]
Nice, thanks for the quick response!
