### ISSUE TITLE
3.0.1 seems to brake drag&drop ordering

### ISSUE THREAD

**Issue by tschale** [jazzband/django-sortedm2m#167]
The items won't drag&drop, but stay in place and get selected. Works on 3.0.0, on 3.0.1 I get following error in Chrome:
![image](https://user-images.githubusercontent.com/5681839/88289899-3c112880-ccf6-11ea-9fad-6bd0a730e9e6.png)

Django 2.2.14
python 3.7.4

**Comment by clintonb** [comment]
This is most likely the result of https://github.com/jazzband/django-sortedm2m/pull/149. I will investigate later today.

**Comment by clintonb** [comment]
This will be fixed in 3.0.2, which should be released in about 30 minutes, barring build failures.

**Comment by tschale** [comment]
Nice, thank you!
