### ISSUE TITLE
Popup for creating new entity for relational field is not closing due to js error

### ISSUE THREAD

**Issue by fatalcoder** [jazzband/django-sortedm2m#169]
Django 3.1
django-sortedm2m==3.0.2

```
Uncaught ReferenceError: windowname_to_id is not defined
    at window.<computed> (/static/sortedm2m/widget.js:105)
    at popup_response.js:13
```
 
Problematic call: https://github.com/jazzband/django-sortedm2m/blob/master/sortedm2m/static/sortedm2m/widget.js#L105

Related change on Django: https://github.com/django/django/commit/f982f0bdb8317e75af416595c616943d5025da1e

**Comment by naumanarif21** [comment]
> Django 3.1
> django-sortedm2m==3.0.2
> 
> ```
> Uncaught ReferenceError: windowname_to_id is not defined
>     at window.<computed> (/static/sortedm2m/widget.js:105)
>     at popup_response.js:13
> ```
> 
> Problematic call: https://github.com/jazzband/django-sortedm2m/blob/master/sortedm2m/static/sortedm2m/widget.js#L105
> 
> Related change on Django: [django/django@f982f0b](https://github.com/django/django/commit/f982f0bdb8317e75af416595c616943d5025da1e)

Hey @fatalcoder, Did you find any workaround?

**Comment by fatalcoder** [comment]
Hi, didn't search for any 'cause it's not a big deal for us. The values were updated, only the window didn't close.

You can always redefine the function that was removed from Django.

```
function id_to_windowname(text) {	
        text = text.replace(/\./g, '__dot__');	
        text = text.replace(/\-/g, '__dash__');	
        return text;	
    }
```

and even simplify it to just

```
function id_to_windowname(text) {		
        return text;	
    }
```

**Comment by n3rio** [comment]
Hi, im experiencing the same behavior but with a different JS error message:
![Screenshot from 2021-05-13 14-43-57](https://user-images.githubusercontent.com/17817314/118178932-39ed9700-b3fa-11eb-825f-671f5a00704f.png)
Plus the `Delete` check box is not showing:
![Screenshot from 2021-05-13 14-45-03](https://user-images.githubusercontent.com/17817314/118179067-673a4500-b3fa-11eb-8499-f6990d7e38c0.png)
