### ISSUE TITLE
SortedManyToManyField. Getting an error 

### ISSUE THREAD

**Issue by nehakhatri0108** [jazzband/django-sortedm2m#173]
Hi,

I am using your library sortedm2m.fields - SortedManyToManyField. Getting an error message:

django.db.utils.OperationalError: (1054, "Unknown column 'allscriptsApp_sandeep_processors2.sort_value' in 'order clause'")

**Comment by clintonb** [comment]
Did you generate and apply migrations?

**Comment by xrmx** [comment]
I'm seeing something similar, I'm switching an already available field to SortedManyToManyField. The migrations only changed the m2m field but it did not add sort field in the through table.

**Comment by gsawczuk** [comment]
Did you notice this paragraph?

> Finally, make sure not to have the model listed in any filter_horizontal or filter_vertical tuples inside of your ModelAdmin definitions.

**Comment by derek-adair** [comment]
Closing due to innactivity.
