### ISSUE TITLE
New release with support for django 3.2

### ISSUE THREAD

**Issue by magajh** [jazzband/django-sortedm2m#188]
The edX project is looking forward to using django-sortedm2m with Django 3.2. Here is the associated Github issue https://github.com/edx/upgrades/issues/59

I noticed that PR #184 added support for Django 3.2.
Are there any chances a new version will be released soon? I would be happy to help in case there are any blockers with this.

Thank you in advance!

**Comment by clintonb** [comment]
@jezdez can I get some support with the build: https://github.com/jazzband/django-sortedm2m/runs/3469020610?check_suite_focus=true?

**Comment by chadsaun** [comment]
It looks like Django 3.2 is supported now with release [3.1.0](https://github.com/jazzband/django-sortedm2m/releases/tag/3.1.0)

Can you publish this new version to PyPi?

**Comment by magajh** [comment]
Many thanks, @clintonb @jezdez! 

Are you going to publish the new version to PyPi any time soon?

**Comment by richardbarran** [comment]
Hi @clintonb -  is there anything I can do to help out?

**Comment by awais786** [comment]
Facing issue on django32 and the PR is open with the fix 
https://github.com/jazzband/django-sortedm2m/pull/174

**Comment by clintonb** [comment]
3.1.1 has been released. I had to remove a broken GitHub Action. Sorry for the delay.
